name: 'deploy'

on:
  push:
    branches:
      - main # configure this
  workflow_dispatch: # this allows a manual trigger of deploys as well

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        env:
          GIT_SSH_COMMAND: 'ssh -vvv'
        with:
          branch: 'main' # the branch on the Dokku server to deploy to
          git_push_flags: '-vvv'
          git_remote_url: ${{ secrets.DOKKU_GIT_REMOTE_URL }}
          ssh_host_key: ${{ secrets.DOKKU_SSH_HOST_KEY }}
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          trace: '1'

          