name: Deploy to Dokku Server

on:
  push:
    branches:
      - main # configure this
  workflow_dispatch: # this allows a manual trigger of deploys as well

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: 'main' # the branch on the Dokku server to deploy to
          git_remote_url: ${{ secrets.DOKKU_GIT_REMOTE_URL}}
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}

          